spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    addresses: localhost
    port: 15672
    username: guest
    password: guest
management:
  endpoint:
    web:
      exposure:
        include: bus-refresh