spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
management:
  endpoints:
    web:
      exposure:
        include: "*"