server:
  port: 8975
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: client3
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"

