server:
  port: 8940
spring:
  application:
    name: service-zuul
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    addresses: 10.220.115.21
    port: 5672
    username: guest
    password: guest
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign