server:
  port: 8939
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8900/eureka

spring:
  application:
    name: eureka-ribbon
  zipkin:
    base-url: http://localhost:9411
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    rabbitmq:
      addresses: localhost
      port: 5672
      username: guest
      password: guest
  management:
    endpoints:
      web:
        exposure:
          include: "*"