server:
  port: 8939
spring:
  application:
    name: eureka-ribbon
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    addresses: 10.220.115.21
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"