server:
  port: 8920
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a807966224/sharp/
          search-paths: config-server/src/main/resources/configs
          username:
          password:
      label: master
#  zipkin:
#    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8900/eureka